project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "US Unemployment"
  author:
    - Ming Gao (mg4618)
    - Hugo Hsieh (ph2680)
  repo-url: https://github.com/laurie-gao/US-unemployment
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


